### ISSUE TITLE
OBS v28 support

### ISSUE THREAD

**Issue by BenJamesAndo** [Andersama/obs-asio#119] opened 2022-08-29 00:12 UTC
Hello. I'm running OBS 28 rc2. It says win-asio plugin failed to load. Are there plans to update this to work with OBS 28?

**Comment by JonathanPowe** [comment] 2022-08-30 16:16
Happy to help beta test this with OBS v28.
We have a Behringer Wing mixing desk that we currently use your plugin with OBS v27 to get several mixes from the desk's USB card into OBS for live outputs and recording.

**Comment by arek-pelski** [comment] 2022-08-30 19:03
Happy to help beta test too :-) Focusrite Scarlet and Zoom H6 in multichannel mode... :-)

**Comment by rayabelcode** [comment] 2022-09-01 11:51
I'm in for beta testing as well - Universal Audio Apollo Twin here.

**Comment by Kithron** [comment] 2022-09-01 21:35
I'm willing to test this out as well.

Has a Shure SM7B connected to my Solid State Logic SSL2.

**Comment by foxx1337** [comment] 2022-09-02 01:19
You can try my latest bassasio build [v3.1.2-bassasio](https://github.com/foxx1337/obs-asio/releases/tag/v3.1.2-bassasio). I only do bassasio because I'm using the plugin for Rocksmith 2014 and it works best with that implementation.

**Comment by papahuge** [comment] 2022-09-02 05:29
yup def need update for obs V28
![image](https://user-images.githubusercontent.com/73111061/188065398-e2fc558f-34bc-4233-879b-53c69bbd265d.png)

**Comment by swalsh76** [comment] 2022-09-02 19:10
Also happy to beta test.  I use the older version with my Zoom LiveTrak-12 and it works excellently.

**Comment by BenJamesAndo** [comment] 2022-09-02 21:23
> You can try my latest bassasio build [v3.1.2-bassasio](https://github.com/foxx1337/obs-asio/releases/tag/v3.1.2-bassasio). I only do bassasio because I'm using the plugin for Rocksmith 2014 and it works best with that implementation.

I did some quick tests and your version seems to work great with OBS 28. Thanks!

**Comment by swalsh76** [comment] 2022-09-02 21:24
> I did some quick tests and your version seems to work great with OBS 28. Thanks!

About to try this, will report back.

**Comment by Kithron** [comment] 2022-09-02 22:19
Does not work with my Solid State Logic SSL2. The monitor and output for it work for listening but it will not pick up either channel in the screenshot with a recording.

![Sound Channels](https://user-images.githubusercontent.com/11751970/188241973-f8ea00dd-fff6-4151-8423-1fe3a092625a.png)

**Comment by whentotrade** [comment] 2022-09-03 10:11
> Can confirm the bassario build works. I had to remove "winasio.dll" so it would stop popping up the error message, but aside from that dropping the files from the archive into the 64bit folder was a "drop in" process and I did not have to re-add my audio sources.

Thank you @swalsh76 . I also can confirm bassario build works as drop in replacement.

**Comment by tormyvancool** [comment] 2022-09-04 09:40
WIn-ASO doesn't work with 28. Is it planned an updated release of Win-ASIO please?

**Comment by hockinsk** [comment] 2022-09-04 16:17
Working great with JackRouter ASIO. Good work @foxx1337 
![image](https://user-images.githubusercontent.com/1609513/188323143-46f35f02-03fe-4e79-a984-10550e686428.png)

**Comment by Bratsess** [comment] 2022-09-04 18:39
Hi !
Would be happy to the beta test too !
I'm on M-audio 192/6, with a mic and a bass connected to it.

**Comment by datlaunchystark** [comment] 2022-09-05 08:12
> sasio but OBS crash everytime i t

I have the same problem sadly :(

**Comment by hockinsk** [comment] 2022-09-05 08:34
Remember it's only an asio input capture, if you try and simply connect to the ASIO driver another software has exclusive of and it's not a duplex/loopback ASIO interface, you won't get much working. Using JACK Audio gets around all this, you just drag connections around your ASIO devices as in the screenshot, no need for Duplex or Loopback then.

**Comment by wkpark** [comment] 2022-09-05 09:06
See also https://github.com/Andersama/obs-asio/pull/120
![image](https://user-images.githubusercontent.com/232347/188412210-8cedc5ab-bbba-4b46-92cf-146a4724b8d7.png)

**Comment by hockinsk** [comment] 2022-09-05 09:34
Yep, you'll be fine with Duplex mode, it's Playback mode will probably mute/crash so JACK is a workaround to get Duplex into OBS from Playback only ASIO in my experience.

**Comment by cPathz** [comment] 2022-09-06 02:08
Hello. Would be happy to the beta test too! 
• Presonus Studio1824c
• Zoom H5

**Comment by swalsh76** [comment] 2022-09-06 17:27
A follow-up note:

I was able to get all the tracks and the master outs configured using the bassario build, however on my next stream OBS didn't seem to actually route the sound to my stream itself.  Given that others have had success without that issue it was probably an issue with my OBS specifically, but just something to keep in mind if you see it.  I ended up having to move back to 27.x which is fine for now.

**Comment by Bratsess** [comment] 2022-09-06 17:36
Little update, I used Jack Audio as @hockinsk  suggested, and now it's working perfectly with bassasio build from @foxx1337 !
Thanks a lot to you two !

**Comment by hockinsk** [comment] 2022-09-06 20:58
> Little update, I used Jack Audio as @hockinsk suggested, and now it's working perfectly with bassasio build from @foxx1337 ! Thanks a lot to you two !

Cool. JACK is a bit of git to setup sometimes, but once you got your head around it, super useful with all sorts of ASIO workflow.

**Comment by wkpark** [comment] 2022-09-08 17:40
This is a new asiobass build. (with the asiobass loader fix by pkv with some recent foxx1337 patches)
https://github.com/wkpark/obs-asio/actions/runs/3007072664#artifacts
(this build has no `bassasio.dll` to bypass the license issue and you have to download bassasio.dll by yourself at https://www.un4seen.com/download.php?bassasio14 and extract the `bassasio.dll` into the dir that has the obs-studio executable as `obs-studio/bin/x64/obs64.exe`.)

I will add this PR request again after PR #120 is merged.

**Comment by Andersama** [comment] 2022-09-08 18:19
@tormyvancool no, the asiobass version's got licensing issues, and I'm not actively maintaining the plugin anyway. If you're using it I'm assuming you've built it, you'll have to build it again for each major obs release.

The slight change now is apparently I've got confirmation that the automated builds are supposed to be future proof so I'm going to be reviewing wkpark's PR for the juce build. In theory it should be just a git push to update the build (which means you all should also be able to fork and push to get the automated build when I'm not around).

**Comment by swalsh76** [comment] 2022-09-09 18:18
> @tormyvancool no, the asiobass version's got licensing issues, and I'm not actively maintaining the plugin anyway. If you're using it I'm assuming you've built it, you'll have to build it again for each major obs release.
> 
> The slight change now is apparently I've got confirmation that the automated builds are supposed to be future proof so I'm going to be reviewing wkpark's PR for the juce build. In theory it should be just a git push to update the build (which means you all should also be able to fork and push to get the automated build when I'm not around).

Fantastic news.  Thanks for all your work.  Personally, I'd be in dire straits without this app.

**Comment by tormyvancool** [comment] 2022-09-11 10:44
> @tormyvancool no, the asiobass version's got licensing issues, and I'm not actively maintaining the plugin anyway. If you're using it I'm assuming you've built it, you'll have to build it again for each major obs release.
> 
> The slight change now is apparently I've got confirmation that the automated builds are supposed to be future proof so I'm going to be reviewing wkpark's PR for the juce build. In theory it should be just a git push to update the build (which means you all should also be able to fork and push to get the automated build when I'm not around).

@Andersama I should wait then. Indeed with your ASIO drivers I was able (without instabilities) to route the DAW stereo signal on channel 1 and 2 of OBS and a pilot (guidance voice) microphone channel on audio 3.
3 audio tracks. I've made a video tutorial about, time ago.
Setting up OBS audio as 2.1
This, for me, it's fundamental when I create any tutorial, because I keep my guidance voice separated by the audio signal that should be kept.
The guidance voice; indeed, is useful to me only during editing (montage) then it's deleted.

**Comment by hockinsk** [comment] 2022-09-11 12:08
> @Andersama I should wait then. Indeed with your ASIO drivers I was able (without instabilities) to route the DAW stereo signal on channel 1 and 2 of OBS and a pilot (guidance voice) microphone channel on audio 3. 3 audio tracks. I've made a video tutorial about, time ago. Setting up OBS audio as 2.1 This, for me, it's fundamental when I create any tutorial, because I keep my guidance voice separated by the audio signal that should be kept. The guidance voice; indeed, is useful to me only during editing (montage) then it's deleted.

If you're using a mixture of ASIO, WASAPI/WDM & Application Audio, I would really advise to go the JACK Route anyway, it's what I've always used even before OBS 28 as it just makes everything so simple to hook up and change. Also you are not dependent on your Audio Interface anymore. e.g. if you have a stereo interface only, but want 20 ASIO applications using ASIO together, you can do that and route it to separate inputs in OBS and have full freedom to mix audio with total freedom and it all synced through JACK.
![image](https://user-images.githubusercontent.com/1609513/189526436-24b5d458-1312-43c1-a5bc-b20a2435a9e9.png)

**Comment by tormyvancool** [comment] 2022-09-11 22:13
> > @Andersama I should wait then. Indeed with your ASIO drivers I was able (without instabilities) to route the DAW stereo signal on channel 1 and 2 of OBS and a pilot (guidance voice) microphone channel on audio 3. 3 audio tracks. I've made a video tutorial about, time ago. Setting up OBS audio as 2.1 This, for me, it's fundamental when I create any tutorial, because I keep my guidance voice separated by the audio signal that should be kept. The guidance voice; indeed, is useful to me only during editing (montage) then it's deleted.
> 
> If you're using a mixture of ASIO, WASAPI/WDM & Application Audio, I would really advise to go the JACK Route anyway, it's what I've always used even before OBS 28 as it just makes everything so simple to hook up and change. Also you are not dependent on your Audio Interface anymore. e.g. if you have a stereo interface only, but want 20 ASIO applications using ASIO together, you can do that and route it to separate inputs in OBS and have full freedom to mix audio with total freedom and it all synced through JACK. 

no i don't mix on that way.

**Comment by Andersama** [comment] 2022-09-12 03:54
I might open the discussions tab because this is getting off topic. There's always been a need for work arounds routing wise for the plugin. How you want to accomplish that is up to you.

**Comment by hockinsk** [comment] 2022-09-12 08:30
> I might open the discussions tab because this is getting off topic. There's always been a need for work arounds routing wise for the plugin. How you want to accomplish that is up to you.

Good idea. It wasn't my intention to go off topic with the Jack workaround, simply I could see if people don't have duplex asio devices and use bassasio they will be faced with the 'mute' input issue in OBS 28. As they will come here to discuss, thought it made sense to be a bit more detailed. Several people have contacted me about off this post.

**Comment by tormyvancool** [comment] 2022-09-12 16:50
> I might open the discussions tab because this is getting off topic. There's always been a need for work arounds routing wise for the plugin. How you want to accomplish that is up to you.

Sorry for this. however I found a solution and published a tutorial [https://www.youtube.com/watch?v=Ef3PnOWTRr4](url)

**Comment by Andersama** [comment] 2022-09-12 22:56
@tormyvancool @hockinsk no worries.

**Comment by Andersama** [comment] 2022-09-13 03:09
I've made a pre-release for the juce build available:
https://github.com/Andersama/obs-asio/releases/tag/v3.1.1

Let me know if it works.

**Comment by Mircosfot** [comment] 2022-09-13 12:26
Hi, this Update is still not working on 28.0.1 yet. :-(

**Comment by wkpark** [comment] 2022-09-13 13:00
![image](https://user-images.githubusercontent.com/232347/189906801-7ebf942b-4f24-470a-a3f5-4f85403558ae.png)
![image](https://user-images.githubusercontent.com/232347/189906943-bc49ff97-cb8b-4c69-a5c9-517c57169dad.png)

Recording works nicely with v3.1.1

**Comment by hockinsk** [comment] 2022-09-13 14:04
Seems to be working. Are you sure you're capturing an ASIO input?
![image](https://user-images.githubusercontent.com/1609513/189922315-9515a96b-99ad-4ae0-a4e7-fdd7ca04cd1a.png)

**Comment by Mircosfot** [comment] 2022-09-13 14:27
my GOxLR is also working on recording, but not in streaming :-(

**Comment by Andersama** [comment] 2022-09-13 21:54
If I remember correctly streaming and recording and two different mixes so that you can keep or discard audio, make sure the plugin is being added to both. That'd be a very weird bug for obs to have introduced.

**Comment by BenJamesAndo** [comment] 2022-09-13 22:07
@Mircosfot I had that happen to me. I already had ASIO devices added in before updating the ASIO plugin. I simply removed and re-added the ASIO devices and then audio came through via streaming again.

**Comment by Tempystral** [comment] 2022-09-14 04:19
Not sure if you only want bug reports here, but I can confirm that the 3.11 prerelease works fine for me with a Scarlett 6i6 gen 1 and Windows 10. I didn't even have to recreate my audio sources or anything. Thanks for the update.

**Comment by Andersama** [comment] 2022-09-14 04:28
I'd just open a different issue, and then for everyone who I suppose was up to "beta testing" https://github.com/Andersama/obs-asio/wiki/4.-Supported-devices is where I'd like to keep track of which devices do and do not work. 

I'm sure there'd be a better way in markdown to display it, but in general the device model and the plugin version you've had it work with is good enough in my books.

**Comment by Mircosfot** [comment] 2022-09-14 06:45
i just reinstalled OBS and now it works very well.

**Comment by Andersama** [comment] 2022-09-15 04:55
Alright I'll be closing this then.

**Closed by Andersama** 2022-09-15 04:55 UTC

**Comment by Peacemuser** [comment] 2024-03-25 01:09
> Working great with JackRouter ASIO. Good work @foxx1337 ![image](https://user-images.githubusercontent.com/1609513/188323143-46f35f02-03fe-4e79-a984-10550e686428.png)

How did you get more than 4 input/output channels from OBS?
